#开发配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiaodai_pro?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: yanhui
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  typeAliasesPackage: lzt.xiaodai.cn.entity
  mapperLocations: classpath:mapper/*.xml